cudnn_benchmark: false
cudnn_deterministic: false
use_amp: true
# network architecture

# encoder related
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module: true
    cnn_module_kernel: 15

# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 6
    linear_units: 2048
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

extra_asr_decoder: transformer
extra_asr_decoder_conf:
    input_layer: embed
    num_blocks: 2
    linear_units: 2048
    dropout_rate: 0.1

extra_mt_decoder: transformer
extra_mt_decoder_conf:
    input_layer: embed
    num_blocks: 2
    linear_units: 2048
    dropout_rate: 0.1

# loss related
model_conf:
    asr_weight: 0.3
    mt_weight: 0.0
    mtlalpha: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    
# frontend related 
unused_parameters: true
freeze_param: [
    "frontend.upstream"
]

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_xlsr
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024
    output_size: 100

# frontend: fused
# frontend_conf: 
#     frontends:
#         - frontend_type: default
#           n_fft: 512
#           win_length: 400
#           hop_length: 160

#         - frontend_type: s3prl
#           frontend_conf:
#             upstream: wav2vec2_xlsr
#           download_dir: ./hub
#           multilayer_feature: True

#     align_method: linear_projection
#     proj_dim: 200     

# preencoder: linear
# preencoder_conf:
#     input_size: 400  # Note: If the upstream is changed, please change this value accordingly.
#     output_size: 100

# optimization related
optim: adam
accum_grad: 1
grad_clip: 5
max_epoch: 50
optim_conf:
    lr: 0.0005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

# minibatch related
batch_type: folded
batch_size: 64

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

init: xavier_uniform
