frontend: embed     # embedding + positional encoding
frontend_conf:
    embed_dim: 768
    positional_dropout_rate: 0.3

encoder: transformer
encoder_conf:
    output_size: 768
    attention_heads: 12
    linear_units: 3072
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    attention_dropout_rate: 0.3
    input_layer: null
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 12
    linear_units: 3072
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    self_attention_dropout_rate: 0.3
    src_attention_dropout_rate: 0.3

model_conf:
    token_loss_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false

num_att_plot: 1
log_interval: 100
num_workers: 2
batch_type: numel
batch_bins: 40000000
accum_grad: 1
max_epoch: 200
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.003
    betas:
    - 0.9
    - 0.98
    eps: 0.000000001
    weight_decay: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10000
